name: Test Flask app and upload to server

on: [push, workflow_dispatch]
jobs:
  test_application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v

      - name: Tests have failed
        if: ${{ failure() }}
        run: echo 'Failure! :('

      - name: Tests have passed
        if: ${{ success() }}
        run: echo 'Success! :)'

      - name: Access web server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: root
          password: ${{ secrets.SERVER_PW }}
          script: |
            echo 'Checking server status...'
            systemctl status foobar
