Name: Test Flask app and upload to server

on: push
jobs:
  test_application:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/asetup-python@v2
        with: python-version: '3.10.0'
      
      - name: Install dependencies
        uses: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v